package dk.digitalidentity.ap.api.asdr;

public class KleApiTest {

	// This class is intentionally left empty...
	//
	// The API is generated by Spring Data Rest, and no customization has been
	// made to this API, so testing relies 100% on the tests performed by the
	// vendor of the Spring Data Rest framework
}
