package dk.digitalidentity.ap.api.asdr;

import dk.digitalidentity.ap.api.ApiTestHelper;

public class SearchWordsApiTest extends ApiTestHelper {
	// This class is intentionally left empty...
	//
	// The API is generated by Spring Data Rest, and no customization has been
	// made to this API, so testing relies 100% on the tests performed by the
	// vendor of the Spring Data Rest framework
}
