//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomaenebestyrelseIndgangType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomaenebestyrelseIndgangType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}DomaenebestyrelseNavnKode"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}DomaenebestyrelseReference"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomaenebestyrelseIndgangType", propOrder = {
    "domaenebestyrelseNavnKode",
    "domaenebestyrelseReference"
})
public class DomaenebestyrelseIndgangType {

    @XmlElement(name = "DomaenebestyrelseNavnKode", required = true)
    @XmlSchemaType(name = "string")
    protected DomaenebestyrelseNavnKodeType domaenebestyrelseNavnKode;
    @XmlElement(name = "DomaenebestyrelseReference", required = true)
    protected String domaenebestyrelseReference;

    /**
     * Gets the value of the domaenebestyrelseNavnKode property.
     * 
     * @return
     *     possible object is
     *     {@link DomaenebestyrelseNavnKodeType }
     *     
     */
    public DomaenebestyrelseNavnKodeType getDomaenebestyrelseNavnKode() {
        return domaenebestyrelseNavnKode;
    }

    /**
     * Sets the value of the domaenebestyrelseNavnKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomaenebestyrelseNavnKodeType }
     *     
     */
    public void setDomaenebestyrelseNavnKode(DomaenebestyrelseNavnKodeType value) {
        this.domaenebestyrelseNavnKode = value;
    }

    /**
     * Gets the value of the domaenebestyrelseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomaenebestyrelseReference() {
        return domaenebestyrelseReference;
    }

    /**
     * Sets the value of the domaenebestyrelseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomaenebestyrelseReference(String value) {
        this.domaenebestyrelseReference = value;
    }

}
