//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomaenebestyrelseNavnKodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DomaenebestyrelseNavnKodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bygninger boliger og forsyning"/>
 *     &lt;enumeration value="Social og omsorg"/>
 *     &lt;enumeration value="Erhverv"/>
 *     &lt;enumeration value="Sundhed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DomaenebestyrelseNavnKodeType")
@XmlEnum
public enum DomaenebestyrelseNavnKodeType {

    @XmlEnumValue("Bygninger boliger og forsyning")
    BYGNINGER_BOLIGER_OG_FORSYNING("Bygninger boliger og forsyning"),
    @XmlEnumValue("Social og omsorg")
    SOCIAL_OG_OMSORG("Social og omsorg"),
    @XmlEnumValue("Erhverv")
    ERHVERV("Erhverv"),
    @XmlEnumValue("Sundhed")
    SUNDHED("Sundhed");
    private final String value;

    DomaenebestyrelseNavnKodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DomaenebestyrelseNavnKodeType fromValue(String v) {
        for (DomaenebestyrelseNavnKodeType c: DomaenebestyrelseNavnKodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
