//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormHierarkiHentOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormHierarkiHentOutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:form:1.0.0}ServiceOmraadeIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}ServiceOmraade" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}HovedOmraadeIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}HovedOmraade" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraadeIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraade" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}Opgave" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormHierarkiHentOutputType", propOrder = {
    "serviceOmraadeIndgang",
    "serviceOmraade",
    "hovedOmraadeIndgang",
    "hovedOmraade",
    "opgaveOmraadeIndgang",
    "opgaveOmraade",
    "opgaveIndgang",
    "opgave"
})
public class FormHierarkiHentOutputType {

    @XmlElement(name = "ServiceOmraadeIndgang")
    protected List<ServiceOmraadeIndgangType> serviceOmraadeIndgang;
    @XmlElement(name = "ServiceOmraade")
    protected List<ServiceOmraadeType> serviceOmraade;
    @XmlElement(name = "HovedOmraadeIndgang")
    protected List<HovedOmraadeIndgangType> hovedOmraadeIndgang;
    @XmlElement(name = "HovedOmraade")
    protected List<HovedOmraadeType> hovedOmraade;
    @XmlElement(name = "OpgaveOmraadeIndgang")
    protected List<OpgaveOmraadeIndgangType> opgaveOmraadeIndgang;
    @XmlElement(name = "OpgaveOmraade")
    protected List<OpgaveOmraadeType> opgaveOmraade;
    @XmlElement(name = "OpgaveIndgang")
    protected List<OpgaveIndgangType> opgaveIndgang;
    @XmlElement(name = "Opgave")
    protected List<OpgaveType> opgave;

    /**
     * Gets the value of the serviceOmraadeIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceOmraadeIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceOmraadeIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceOmraadeIndgangType }
     * 
     * 
     */
    public List<ServiceOmraadeIndgangType> getServiceOmraadeIndgang() {
        if (serviceOmraadeIndgang == null) {
            serviceOmraadeIndgang = new ArrayList<ServiceOmraadeIndgangType>();
        }
        return this.serviceOmraadeIndgang;
    }

    /**
     * Gets the value of the serviceOmraade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceOmraade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceOmraade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceOmraadeType }
     * 
     * 
     */
    public List<ServiceOmraadeType> getServiceOmraade() {
        if (serviceOmraade == null) {
            serviceOmraade = new ArrayList<ServiceOmraadeType>();
        }
        return this.serviceOmraade;
    }

    /**
     * Gets the value of the hovedOmraadeIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hovedOmraadeIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHovedOmraadeIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HovedOmraadeIndgangType }
     * 
     * 
     */
    public List<HovedOmraadeIndgangType> getHovedOmraadeIndgang() {
        if (hovedOmraadeIndgang == null) {
            hovedOmraadeIndgang = new ArrayList<HovedOmraadeIndgangType>();
        }
        return this.hovedOmraadeIndgang;
    }

    /**
     * Gets the value of the hovedOmraade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hovedOmraade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHovedOmraade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HovedOmraadeType }
     * 
     * 
     */
    public List<HovedOmraadeType> getHovedOmraade() {
        if (hovedOmraade == null) {
            hovedOmraade = new ArrayList<HovedOmraadeType>();
        }
        return this.hovedOmraade;
    }

    /**
     * Gets the value of the opgaveOmraadeIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgaveOmraadeIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgaveOmraadeIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveOmraadeIndgangType }
     * 
     * 
     */
    public List<OpgaveOmraadeIndgangType> getOpgaveOmraadeIndgang() {
        if (opgaveOmraadeIndgang == null) {
            opgaveOmraadeIndgang = new ArrayList<OpgaveOmraadeIndgangType>();
        }
        return this.opgaveOmraadeIndgang;
    }

    /**
     * Gets the value of the opgaveOmraade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgaveOmraade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgaveOmraade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveOmraadeType }
     * 
     * 
     */
    public List<OpgaveOmraadeType> getOpgaveOmraade() {
        if (opgaveOmraade == null) {
            opgaveOmraade = new ArrayList<OpgaveOmraadeType>();
        }
        return this.opgaveOmraade;
    }

    /**
     * Gets the value of the opgaveIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgaveIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgaveIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveIndgangType }
     * 
     * 
     */
    public List<OpgaveIndgangType> getOpgaveIndgang() {
        if (opgaveIndgang == null) {
            opgaveIndgang = new ArrayList<OpgaveIndgangType>();
        }
        return this.opgaveIndgang;
    }

    /**
     * Gets the value of the opgave property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgave property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgave().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveType }
     * 
     * 
     */
    public List<OpgaveType> getOpgave() {
        if (opgave == null) {
            opgave = new ArrayList<OpgaveType>();
        }
        return this.opgave;
    }

}
