//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormIndgangType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormIndgangType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:form:1.0.0}NavnTekst"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}ServiceOmraadeNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}HovedOmraadeNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraadeNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}FormReference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormIndgangType", propOrder = {
    "navnTekst",
    "serviceOmraadeNummerIdentifikator",
    "hovedOmraadeNummerIdentifikator",
    "opgaveOmraadeNummerIdentifikator",
    "opgaveNummerIdentifikator",
    "formReference"
})
public class FormIndgangType {

    @XmlElement(name = "NavnTekst")
    protected String navnTekst;
    @XmlElement(name = "ServiceOmraadeNummerIdentifikator")
    protected String serviceOmraadeNummerIdentifikator;
    @XmlElement(name = "HovedOmraadeNummerIdentifikator")
    protected String hovedOmraadeNummerIdentifikator;
    @XmlElement(name = "OpgaveOmraadeNummerIdentifikator")
    protected String opgaveOmraadeNummerIdentifikator;
    @XmlElement(name = "OpgaveNummerIdentifikator")
    protected String opgaveNummerIdentifikator;
    @XmlElement(name = "FormReference")
    protected String formReference;

    /**
     * Gets the value of the navnTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavnTekst() {
        return navnTekst;
    }

    /**
     * Sets the value of the navnTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavnTekst(String value) {
        this.navnTekst = value;
    }

    /**
     * Gets the value of the serviceOmraadeNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceOmraadeNummerIdentifikator() {
        return serviceOmraadeNummerIdentifikator;
    }

    /**
     * Sets the value of the serviceOmraadeNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceOmraadeNummerIdentifikator(String value) {
        this.serviceOmraadeNummerIdentifikator = value;
    }

    /**
     * Gets the value of the hovedOmraadeNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedOmraadeNummerIdentifikator() {
        return hovedOmraadeNummerIdentifikator;
    }

    /**
     * Sets the value of the hovedOmraadeNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedOmraadeNummerIdentifikator(String value) {
        this.hovedOmraadeNummerIdentifikator = value;
    }

    /**
     * Gets the value of the opgaveOmraadeNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpgaveOmraadeNummerIdentifikator() {
        return opgaveOmraadeNummerIdentifikator;
    }

    /**
     * Sets the value of the opgaveOmraadeNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpgaveOmraadeNummerIdentifikator(String value) {
        this.opgaveOmraadeNummerIdentifikator = value;
    }

    /**
     * Gets the value of the opgaveNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpgaveNummerIdentifikator() {
        return opgaveNummerIdentifikator;
    }

    /**
     * Sets the value of the opgaveNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpgaveNummerIdentifikator(String value) {
        this.opgaveNummerIdentifikator = value;
    }

    /**
     * Gets the value of the formReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormReference() {
        return formReference;
    }

    /**
     * Sets the value of the formReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormReference(String value) {
        this.formReference = value;
    }

}
