//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HovedOmraadeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HovedOmraadeType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oio:form:1.0.0}HovedOmraadeBaseType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraade" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraadeIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HovedOmraadeType", propOrder = {
    "opgaveOmraade",
    "opgaveOmraadeIndgang"
})
public class HovedOmraadeType
    extends HovedOmraadeBaseType
{

    @XmlElement(name = "OpgaveOmraade")
    protected List<OpgaveOmraadeType> opgaveOmraade;
    @XmlElement(name = "OpgaveOmraadeIndgang")
    protected List<OpgaveOmraadeIndgangType> opgaveOmraadeIndgang;

    /**
     * Gets the value of the opgaveOmraade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgaveOmraade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgaveOmraade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveOmraadeType }
     * 
     * 
     */
    public List<OpgaveOmraadeType> getOpgaveOmraade() {
        if (opgaveOmraade == null) {
            opgaveOmraade = new ArrayList<OpgaveOmraadeType>();
        }
        return this.opgaveOmraade;
    }

    /**
     * Gets the value of the opgaveOmraadeIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opgaveOmraadeIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpgaveOmraadeIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpgaveOmraadeIndgangType }
     * 
     * 
     */
    public List<OpgaveOmraadeIndgangType> getOpgaveOmraadeIndgang() {
        if (opgaveOmraadeIndgang == null) {
            opgaveOmraadeIndgang = new ArrayList<OpgaveOmraadeIndgangType>();
        }
        return this.opgaveOmraadeIndgang;
    }

}
