//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HovedOmraadeBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HovedOmraadeBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oio:form:1.0.0}ObjektType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}HovedOmraadeNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}FinanslovIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HovedOmraadeBaseType", propOrder = {
    "hovedOmraadeNummerIdentifikator",
    "finanslovIndgang"
})
@XmlSeeAlso({
    HovedOmraadeType.class
})
public class HovedOmraadeBaseType
    extends ObjektType
{

    @XmlElement(name = "HovedOmraadeNummerIdentifikator", required = true)
    protected String hovedOmraadeNummerIdentifikator;
    @XmlElement(name = "FinanslovIndgang")
    protected List<FinanslovIndgangType> finanslovIndgang;

    /**
     * Gets the value of the hovedOmraadeNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedOmraadeNummerIdentifikator() {
        return hovedOmraadeNummerIdentifikator;
    }

    /**
     * Sets the value of the hovedOmraadeNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedOmraadeNummerIdentifikator(String value) {
        this.hovedOmraadeNummerIdentifikator = value;
    }

    /**
     * Gets the value of the finanslovIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finanslovIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinanslovIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinanslovIndgangType }
     * 
     * 
     */
    public List<FinanslovIndgangType> getFinanslovIndgang() {
        if (finanslovIndgang == null) {
            finanslovIndgang = new ArrayList<FinanslovIndgangType>();
        }
        return this.finanslovIndgang;
    }

}
