//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LovgivningIndgangType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LovgivningIndgangType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}LovgivningTekst"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}LovgivningReference"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LovgivningIndgangType", propOrder = {
    "lovgivningTekst",
    "lovgivningReference"
})
public class LovgivningIndgangType {

    @XmlElement(name = "LovgivningTekst", required = true)
    protected String lovgivningTekst;
    @XmlElement(name = "LovgivningReference", required = true)
    protected String lovgivningReference;

    /**
     * Gets the value of the lovgivningTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLovgivningTekst() {
        return lovgivningTekst;
    }

    /**
     * Sets the value of the lovgivningTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLovgivningTekst(String value) {
        this.lovgivningTekst = value;
    }

    /**
     * Gets the value of the lovgivningReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLovgivningReference() {
        return lovgivningReference;
    }

    /**
     * Sets the value of the lovgivningReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLovgivningReference(String value) {
        this.lovgivningReference = value;
    }

}
