//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MyndighedIndgangType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MyndighedIndgangType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}MyndighedNavn"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}MyndighedReference"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MyndighedIndgangType", propOrder = {
    "myndighedNavn",
    "myndighedReference"
})
public class MyndighedIndgangType {

    @XmlElement(name = "MyndighedNavn", required = true)
    protected String myndighedNavn;
    @XmlElement(name = "MyndighedReference", required = true)
    protected String myndighedReference;

    /**
     * Gets the value of the myndighedNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyndighedNavn() {
        return myndighedNavn;
    }

    /**
     * Sets the value of the myndighedNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyndighedNavn(String value) {
        this.myndighedNavn = value;
    }

    /**
     * Gets the value of the myndighedReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyndighedReference() {
        return myndighedReference;
    }

    /**
     * Sets the value of the myndighedReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyndighedReference(String value) {
        this.myndighedReference = value;
    }

}
