//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.formonline.formoperationer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FinanslovIndgang_QNAME = new QName("urn:oio:form:1.0.0", "FinanslovIndgang");
    private final static QName _FinanslovReference_QNAME = new QName("urn:oio:form:1.0.0", "FinanslovReference");
    private final static QName _OpgaverFinanslovHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverFinanslovHentOutput");
    private final static QName _DomaenebestyrelseNavnKode_QNAME = new QName("urn:oio:form:1.0.0", "DomaenebestyrelseNavnKode");
    private final static QName _ServiceOmraadeIndgang_QNAME = new QName("urn:oio:form:1.0.0", "ServiceOmraadeIndgang");
    private final static QName _Version_QNAME = new QName("urn:oio:form:1.0.0", "Version");
    private final static QName _BeskrivelseTekst_QNAME = new QName("urn:oio:form:1.0.0", "BeskrivelseTekst");
    private final static QName _LovgivningTekst_QNAME = new QName("urn:oio:form:1.0.0", "LovgivningTekst");
    private final static QName _FinanslovParagrafTekst_QNAME = new QName("urn:oio:form:1.0.0", "FinanslovParagrafTekst");
    private final static QName _FormHierarkiHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "FormHierarkiHentOutput");
    private final static QName _OpgaverLovgivningHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverLovgivningHentOutput");
    private final static QName _DomaenebestyrelseIndgang_QNAME = new QName("urn:oio:form:1.0.0", "DomaenebestyrelseIndgang");
    private final static QName _OpgaverLovgivningHentInput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverLovgivningHentInput");
    private final static QName _MyndighedReference_QNAME = new QName("urn:oio:form:1.0.0", "MyndighedReference");
    private final static QName _LovgivningReference_QNAME = new QName("urn:oio:form:1.0.0", "LovgivningReference");
    private final static QName _FormReference_QNAME = new QName("urn:oio:form:1.0.0", "FormReference");
    private final static QName _UuidIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "UuidIdentifikator");
    private final static QName _NavnTekst_QNAME = new QName("urn:oio:form:1.0.0", "NavnTekst");
    private final static QName _MyndighedNavn_QNAME = new QName("urn:oio:form:1.0.0", "MyndighedNavn");
    private final static QName _KLEindgang_QNAME = new QName("urn:oio:form:1.0.0", "KLEindgang");
    private final static QName _OprettetDato_QNAME = new QName("urn:oio:form:1.0.0", "OprettetDato");
    private final static QName _Objekt_QNAME = new QName("urn:oio:form:1.0.0", "Objekt");
    private final static QName _OpgaverDomaenebestyrelseHentInput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverDomaenebestyrelseHentInput");
    private final static QName _UdgaaetDato_QNAME = new QName("urn:oio:form:1.0.0", "UdgaaetDato");
    private final static QName _ServiceOmraade_QNAME = new QName("urn:oio:form:1.0.0", "ServiceOmraade");
    private final static QName _OpgaveOmraadeIndgang_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveOmraadeIndgang");
    private final static QName _KLEReference_QNAME = new QName("urn:oio:form:1.0.0", "KLEReference");
    private final static QName _OpgaverDomaenebestyrelseHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverDomaenebestyrelseHentOutput");
    private final static QName _FormIndgang_QNAME = new QName("urn:oio:form:1.0.0", "FormIndgang");
    private final static QName _OpgaverFinanslovHentInput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverFinanslovHentInput");
    private final static QName _ServiceOmraadeNummerIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "ServiceOmraadeNummerIdentifikator");
    private final static QName _EmneHandlingFacetTekst_QNAME = new QName("urn:oio:form:1.0.0", "EmneHandlingFacetTekst");
    private final static QName _Opgave_QNAME = new QName("urn:oio:form:1.0.0", "Opgave");
    private final static QName _LovgivningIndgang_QNAME = new QName("urn:oio:form:1.0.0", "LovgivningIndgang");
    private final static QName _DomaenebestyrelseReference_QNAME = new QName("urn:oio:form:1.0.0", "DomaenebestyrelseReference");
    private final static QName _FormDybdeKvantitet_QNAME = new QName("urn:oio:form:1.0.0", "FormDybdeKvantitet");
    private final static QName _HovedOmraadeBase_QNAME = new QName("urn:oio:form:1.0.0", "HovedOmraadeBase");
    private final static QName _OrdenMaal_QNAME = new QName("urn:oio:form:1.0.0", "OrdenMaal");
    private final static QName _FormHierarkiHentInput_QNAME = new QName("urn:oio:form:1.0.0", "FormHierarkiHentInput");
    private final static QName _ServiceOmraadeBase_QNAME = new QName("urn:oio:form:1.0.0", "ServiceOmraadeBase");
    private final static QName _SoegeordTekst_QNAME = new QName("urn:oio:form:1.0.0", "SoegeordTekst");
    private final static QName _HovedOmraadeIndgang_QNAME = new QName("urn:oio:form:1.0.0", "HovedOmraadeIndgang");
    private final static QName _OpgaveOmraadeBase_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveOmraadeBase");
    private final static QName _MyndighedIndgang_QNAME = new QName("urn:oio:form:1.0.0", "MyndighedIndgang");
    private final static QName _OpgaverMyndighedHentInput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverMyndighedHentInput");
    private final static QName _HovedOmraade_QNAME = new QName("urn:oio:form:1.0.0", "HovedOmraade");
    private final static QName _OpgaverKLEHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverKLEHentOutput");
    private final static QName _Soegeord_QNAME = new QName("urn:oio:form:1.0.0", "Soegeord");
    private final static QName _VersionIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "VersionIdentifikator");
    private final static QName _OpgaveOmraadeNummerIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveOmraadeNummerIdentifikator");
    private final static QName _OpgaverMyndighedHentOutput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverMyndighedHentOutput");
    private final static QName _OpgaveOmraade_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveOmraade");
    private final static QName _OpgaveNummerIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveNummerIdentifikator");
    private final static QName _OpgaveIndgang_QNAME = new QName("urn:oio:form:1.0.0", "OpgaveIndgang");
    private final static QName _HovedOmraadeNummerIdentifikator_QNAME = new QName("urn:oio:form:1.0.0", "HovedOmraadeNummerIdentifikator");
    private final static QName _RettetDato_QNAME = new QName("urn:oio:form:1.0.0", "RettetDato");
    private final static QName _OpgaverKLEHentInput_QNAME = new QName("urn:oio:form:1.0.0", "OpgaverKLEHentInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.formonline.formoperationer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpgaverLovgivningHentOutputType }
     * 
     */
    public OpgaverLovgivningHentOutputType createOpgaverLovgivningHentOutputType() {
        return new OpgaverLovgivningHentOutputType();
    }

    /**
     * Create an instance of {@link DomaenebestyrelseIndgangType }
     * 
     */
    public DomaenebestyrelseIndgangType createDomaenebestyrelseIndgangType() {
        return new DomaenebestyrelseIndgangType();
    }

    /**
     * Create an instance of {@link OpgaverLovgivningHentInputType }
     * 
     */
    public OpgaverLovgivningHentInputType createOpgaverLovgivningHentInputType() {
        return new OpgaverLovgivningHentInputType();
    }

    /**
     * Create an instance of {@link FormHierarkiHentOutputType }
     * 
     */
    public FormHierarkiHentOutputType createFormHierarkiHentOutputType() {
        return new FormHierarkiHentOutputType();
    }

    /**
     * Create an instance of {@link ServiceOmraadeIndgangType }
     * 
     */
    public ServiceOmraadeIndgangType createServiceOmraadeIndgangType() {
        return new ServiceOmraadeIndgangType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link OpgaverFinanslovHentOutputType }
     * 
     */
    public OpgaverFinanslovHentOutputType createOpgaverFinanslovHentOutputType() {
        return new OpgaverFinanslovHentOutputType();
    }

    /**
     * Create an instance of {@link FinanslovIndgangType }
     * 
     */
    public FinanslovIndgangType createFinanslovIndgangType() {
        return new FinanslovIndgangType();
    }

    /**
     * Create an instance of {@link OpgaveType }
     * 
     */
    public OpgaveType createOpgaveType() {
        return new OpgaveType();
    }

    /**
     * Create an instance of {@link LovgivningIndgangType }
     * 
     */
    public LovgivningIndgangType createLovgivningIndgangType() {
        return new LovgivningIndgangType();
    }

    /**
     * Create an instance of {@link FormIndgangType }
     * 
     */
    public FormIndgangType createFormIndgangType() {
        return new FormIndgangType();
    }

    /**
     * Create an instance of {@link OpgaverFinanslovHentInputType }
     * 
     */
    public OpgaverFinanslovHentInputType createOpgaverFinanslovHentInputType() {
        return new OpgaverFinanslovHentInputType();
    }

    /**
     * Create an instance of {@link ServiceOmraadeType }
     * 
     */
    public ServiceOmraadeType createServiceOmraadeType() {
        return new ServiceOmraadeType();
    }

    /**
     * Create an instance of {@link OpgaveOmraadeIndgangType }
     * 
     */
    public OpgaveOmraadeIndgangType createOpgaveOmraadeIndgangType() {
        return new OpgaveOmraadeIndgangType();
    }

    /**
     * Create an instance of {@link OpgaverDomaenebestyrelseHentOutputType }
     * 
     */
    public OpgaverDomaenebestyrelseHentOutputType createOpgaverDomaenebestyrelseHentOutputType() {
        return new OpgaverDomaenebestyrelseHentOutputType();
    }

    /**
     * Create an instance of {@link ObjektType }
     * 
     */
    public ObjektType createObjektType() {
        return new ObjektType();
    }

    /**
     * Create an instance of {@link OpgaverDomaenebestyrelseHentInputType }
     * 
     */
    public OpgaverDomaenebestyrelseHentInputType createOpgaverDomaenebestyrelseHentInputType() {
        return new OpgaverDomaenebestyrelseHentInputType();
    }

    /**
     * Create an instance of {@link KLEindgangType }
     * 
     */
    public KLEindgangType createKLEindgangType() {
        return new KLEindgangType();
    }

    /**
     * Create an instance of {@link OpgaveOmraadeBaseType }
     * 
     */
    public OpgaveOmraadeBaseType createOpgaveOmraadeBaseType() {
        return new OpgaveOmraadeBaseType();
    }

    /**
     * Create an instance of {@link MyndighedIndgangType }
     * 
     */
    public MyndighedIndgangType createMyndighedIndgangType() {
        return new MyndighedIndgangType();
    }

    /**
     * Create an instance of {@link ServiceOmraadeBaseType }
     * 
     */
    public ServiceOmraadeBaseType createServiceOmraadeBaseType() {
        return new ServiceOmraadeBaseType();
    }

    /**
     * Create an instance of {@link HovedOmraadeIndgangType }
     * 
     */
    public HovedOmraadeIndgangType createHovedOmraadeIndgangType() {
        return new HovedOmraadeIndgangType();
    }

    /**
     * Create an instance of {@link HovedOmraadeBaseType }
     * 
     */
    public HovedOmraadeBaseType createHovedOmraadeBaseType() {
        return new HovedOmraadeBaseType();
    }

    /**
     * Create an instance of {@link FormHierarkiHentInputType }
     * 
     */
    public FormHierarkiHentInputType createFormHierarkiHentInputType() {
        return new FormHierarkiHentInputType();
    }

    /**
     * Create an instance of {@link OpgaverKLEHentInputType }
     * 
     */
    public OpgaverKLEHentInputType createOpgaverKLEHentInputType() {
        return new OpgaverKLEHentInputType();
    }

    /**
     * Create an instance of {@link OpgaveIndgangType }
     * 
     */
    public OpgaveIndgangType createOpgaveIndgangType() {
        return new OpgaveIndgangType();
    }

    /**
     * Create an instance of {@link OpgaverMyndighedHentOutputType }
     * 
     */
    public OpgaverMyndighedHentOutputType createOpgaverMyndighedHentOutputType() {
        return new OpgaverMyndighedHentOutputType();
    }

    /**
     * Create an instance of {@link OpgaveOmraadeType }
     * 
     */
    public OpgaveOmraadeType createOpgaveOmraadeType() {
        return new OpgaveOmraadeType();
    }

    /**
     * Create an instance of {@link OpgaverKLEHentOutputType }
     * 
     */
    public OpgaverKLEHentOutputType createOpgaverKLEHentOutputType() {
        return new OpgaverKLEHentOutputType();
    }

    /**
     * Create an instance of {@link SoegeordType }
     * 
     */
    public SoegeordType createSoegeordType() {
        return new SoegeordType();
    }

    /**
     * Create an instance of {@link HovedOmraadeType }
     * 
     */
    public HovedOmraadeType createHovedOmraadeType() {
        return new HovedOmraadeType();
    }

    /**
     * Create an instance of {@link OpgaverMyndighedHentInputType }
     * 
     */
    public OpgaverMyndighedHentInputType createOpgaverMyndighedHentInputType() {
        return new OpgaverMyndighedHentInputType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FinanslovIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FinanslovIndgang")
    public JAXBElement<FinanslovIndgangType> createFinanslovIndgang(FinanslovIndgangType value) {
        return new JAXBElement<FinanslovIndgangType>(_FinanslovIndgang_QNAME, FinanslovIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FinanslovReference")
    public JAXBElement<String> createFinanslovReference(String value) {
        return new JAXBElement<String>(_FinanslovReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverFinanslovHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverFinanslovHentOutput")
    public JAXBElement<OpgaverFinanslovHentOutputType> createOpgaverFinanslovHentOutput(OpgaverFinanslovHentOutputType value) {
        return new JAXBElement<OpgaverFinanslovHentOutputType>(_OpgaverFinanslovHentOutput_QNAME, OpgaverFinanslovHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomaenebestyrelseNavnKodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "DomaenebestyrelseNavnKode")
    public JAXBElement<DomaenebestyrelseNavnKodeType> createDomaenebestyrelseNavnKode(DomaenebestyrelseNavnKodeType value) {
        return new JAXBElement<DomaenebestyrelseNavnKodeType>(_DomaenebestyrelseNavnKode_QNAME, DomaenebestyrelseNavnKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceOmraadeIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "ServiceOmraadeIndgang")
    public JAXBElement<ServiceOmraadeIndgangType> createServiceOmraadeIndgang(ServiceOmraadeIndgangType value) {
        return new JAXBElement<ServiceOmraadeIndgangType>(_ServiceOmraadeIndgang_QNAME, ServiceOmraadeIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "Version")
    public JAXBElement<VersionType> createVersion(VersionType value) {
        return new JAXBElement<VersionType>(_Version_QNAME, VersionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "BeskrivelseTekst")
    public JAXBElement<String> createBeskrivelseTekst(String value) {
        return new JAXBElement<String>(_BeskrivelseTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "LovgivningTekst")
    public JAXBElement<String> createLovgivningTekst(String value) {
        return new JAXBElement<String>(_LovgivningTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FinanslovParagrafTekst")
    public JAXBElement<String> createFinanslovParagrafTekst(String value) {
        return new JAXBElement<String>(_FinanslovParagrafTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormHierarkiHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FormHierarkiHentOutput")
    public JAXBElement<FormHierarkiHentOutputType> createFormHierarkiHentOutput(FormHierarkiHentOutputType value) {
        return new JAXBElement<FormHierarkiHentOutputType>(_FormHierarkiHentOutput_QNAME, FormHierarkiHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverLovgivningHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverLovgivningHentOutput")
    public JAXBElement<OpgaverLovgivningHentOutputType> createOpgaverLovgivningHentOutput(OpgaverLovgivningHentOutputType value) {
        return new JAXBElement<OpgaverLovgivningHentOutputType>(_OpgaverLovgivningHentOutput_QNAME, OpgaverLovgivningHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomaenebestyrelseIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "DomaenebestyrelseIndgang")
    public JAXBElement<DomaenebestyrelseIndgangType> createDomaenebestyrelseIndgang(DomaenebestyrelseIndgangType value) {
        return new JAXBElement<DomaenebestyrelseIndgangType>(_DomaenebestyrelseIndgang_QNAME, DomaenebestyrelseIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverLovgivningHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverLovgivningHentInput")
    public JAXBElement<OpgaverLovgivningHentInputType> createOpgaverLovgivningHentInput(OpgaverLovgivningHentInputType value) {
        return new JAXBElement<OpgaverLovgivningHentInputType>(_OpgaverLovgivningHentInput_QNAME, OpgaverLovgivningHentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "MyndighedReference")
    public JAXBElement<String> createMyndighedReference(String value) {
        return new JAXBElement<String>(_MyndighedReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "LovgivningReference")
    public JAXBElement<String> createLovgivningReference(String value) {
        return new JAXBElement<String>(_LovgivningReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FormReference")
    public JAXBElement<String> createFormReference(String value) {
        return new JAXBElement<String>(_FormReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "UuidIdentifikator")
    public JAXBElement<String> createUuidIdentifikator(String value) {
        return new JAXBElement<String>(_UuidIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "NavnTekst")
    public JAXBElement<String> createNavnTekst(String value) {
        return new JAXBElement<String>(_NavnTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "MyndighedNavn")
    public JAXBElement<String> createMyndighedNavn(String value) {
        return new JAXBElement<String>(_MyndighedNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KLEindgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "KLEindgang")
    public JAXBElement<KLEindgangType> createKLEindgang(KLEindgangType value) {
        return new JAXBElement<KLEindgangType>(_KLEindgang_QNAME, KLEindgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OprettetDato")
    public JAXBElement<XMLGregorianCalendar> createOprettetDato(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OprettetDato_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjektType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "Objekt")
    public JAXBElement<ObjektType> createObjekt(ObjektType value) {
        return new JAXBElement<ObjektType>(_Objekt_QNAME, ObjektType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverDomaenebestyrelseHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverDomaenebestyrelseHentInput")
    public JAXBElement<OpgaverDomaenebestyrelseHentInputType> createOpgaverDomaenebestyrelseHentInput(OpgaverDomaenebestyrelseHentInputType value) {
        return new JAXBElement<OpgaverDomaenebestyrelseHentInputType>(_OpgaverDomaenebestyrelseHentInput_QNAME, OpgaverDomaenebestyrelseHentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "UdgaaetDato")
    public JAXBElement<XMLGregorianCalendar> createUdgaaetDato(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UdgaaetDato_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceOmraadeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "ServiceOmraade")
    public JAXBElement<ServiceOmraadeType> createServiceOmraade(ServiceOmraadeType value) {
        return new JAXBElement<ServiceOmraadeType>(_ServiceOmraade_QNAME, ServiceOmraadeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaveOmraadeIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveOmraadeIndgang")
    public JAXBElement<OpgaveOmraadeIndgangType> createOpgaveOmraadeIndgang(OpgaveOmraadeIndgangType value) {
        return new JAXBElement<OpgaveOmraadeIndgangType>(_OpgaveOmraadeIndgang_QNAME, OpgaveOmraadeIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "KLEReference")
    public JAXBElement<String> createKLEReference(String value) {
        return new JAXBElement<String>(_KLEReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverDomaenebestyrelseHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverDomaenebestyrelseHentOutput")
    public JAXBElement<OpgaverDomaenebestyrelseHentOutputType> createOpgaverDomaenebestyrelseHentOutput(OpgaverDomaenebestyrelseHentOutputType value) {
        return new JAXBElement<OpgaverDomaenebestyrelseHentOutputType>(_OpgaverDomaenebestyrelseHentOutput_QNAME, OpgaverDomaenebestyrelseHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FormIndgang")
    public JAXBElement<FormIndgangType> createFormIndgang(FormIndgangType value) {
        return new JAXBElement<FormIndgangType>(_FormIndgang_QNAME, FormIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverFinanslovHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverFinanslovHentInput")
    public JAXBElement<OpgaverFinanslovHentInputType> createOpgaverFinanslovHentInput(OpgaverFinanslovHentInputType value) {
        return new JAXBElement<OpgaverFinanslovHentInputType>(_OpgaverFinanslovHentInput_QNAME, OpgaverFinanslovHentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "ServiceOmraadeNummerIdentifikator")
    public JAXBElement<String> createServiceOmraadeNummerIdentifikator(String value) {
        return new JAXBElement<String>(_ServiceOmraadeNummerIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "EmneHandlingFacetTekst")
    public JAXBElement<String> createEmneHandlingFacetTekst(String value) {
        return new JAXBElement<String>(_EmneHandlingFacetTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "Opgave")
    public JAXBElement<OpgaveType> createOpgave(OpgaveType value) {
        return new JAXBElement<OpgaveType>(_Opgave_QNAME, OpgaveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LovgivningIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "LovgivningIndgang")
    public JAXBElement<LovgivningIndgangType> createLovgivningIndgang(LovgivningIndgangType value) {
        return new JAXBElement<LovgivningIndgangType>(_LovgivningIndgang_QNAME, LovgivningIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "DomaenebestyrelseReference")
    public JAXBElement<String> createDomaenebestyrelseReference(String value) {
        return new JAXBElement<String>(_DomaenebestyrelseReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FormDybdeKvantitet")
    public JAXBElement<BigInteger> createFormDybdeKvantitet(BigInteger value) {
        return new JAXBElement<BigInteger>(_FormDybdeKvantitet_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HovedOmraadeBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "HovedOmraadeBase")
    public JAXBElement<HovedOmraadeBaseType> createHovedOmraadeBase(HovedOmraadeBaseType value) {
        return new JAXBElement<HovedOmraadeBaseType>(_HovedOmraadeBase_QNAME, HovedOmraadeBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OrdenMaal")
    public JAXBElement<BigInteger> createOrdenMaal(BigInteger value) {
        return new JAXBElement<BigInteger>(_OrdenMaal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormHierarkiHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "FormHierarkiHentInput")
    public JAXBElement<FormHierarkiHentInputType> createFormHierarkiHentInput(FormHierarkiHentInputType value) {
        return new JAXBElement<FormHierarkiHentInputType>(_FormHierarkiHentInput_QNAME, FormHierarkiHentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceOmraadeBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "ServiceOmraadeBase")
    public JAXBElement<ServiceOmraadeBaseType> createServiceOmraadeBase(ServiceOmraadeBaseType value) {
        return new JAXBElement<ServiceOmraadeBaseType>(_ServiceOmraadeBase_QNAME, ServiceOmraadeBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "SoegeordTekst")
    public JAXBElement<String> createSoegeordTekst(String value) {
        return new JAXBElement<String>(_SoegeordTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HovedOmraadeIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "HovedOmraadeIndgang")
    public JAXBElement<HovedOmraadeIndgangType> createHovedOmraadeIndgang(HovedOmraadeIndgangType value) {
        return new JAXBElement<HovedOmraadeIndgangType>(_HovedOmraadeIndgang_QNAME, HovedOmraadeIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaveOmraadeBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveOmraadeBase")
    public JAXBElement<OpgaveOmraadeBaseType> createOpgaveOmraadeBase(OpgaveOmraadeBaseType value) {
        return new JAXBElement<OpgaveOmraadeBaseType>(_OpgaveOmraadeBase_QNAME, OpgaveOmraadeBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyndighedIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "MyndighedIndgang")
    public JAXBElement<MyndighedIndgangType> createMyndighedIndgang(MyndighedIndgangType value) {
        return new JAXBElement<MyndighedIndgangType>(_MyndighedIndgang_QNAME, MyndighedIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverMyndighedHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverMyndighedHentInput")
    public JAXBElement<OpgaverMyndighedHentInputType> createOpgaverMyndighedHentInput(OpgaverMyndighedHentInputType value) {
        return new JAXBElement<OpgaverMyndighedHentInputType>(_OpgaverMyndighedHentInput_QNAME, OpgaverMyndighedHentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HovedOmraadeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "HovedOmraade")
    public JAXBElement<HovedOmraadeType> createHovedOmraade(HovedOmraadeType value) {
        return new JAXBElement<HovedOmraadeType>(_HovedOmraade_QNAME, HovedOmraadeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverKLEHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverKLEHentOutput")
    public JAXBElement<OpgaverKLEHentOutputType> createOpgaverKLEHentOutput(OpgaverKLEHentOutputType value) {
        return new JAXBElement<OpgaverKLEHentOutputType>(_OpgaverKLEHentOutput_QNAME, OpgaverKLEHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegeordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "Soegeord")
    public JAXBElement<SoegeordType> createSoegeord(SoegeordType value) {
        return new JAXBElement<SoegeordType>(_Soegeord_QNAME, SoegeordType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "VersionIdentifikator")
    public JAXBElement<String> createVersionIdentifikator(String value) {
        return new JAXBElement<String>(_VersionIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveOmraadeNummerIdentifikator")
    public JAXBElement<String> createOpgaveOmraadeNummerIdentifikator(String value) {
        return new JAXBElement<String>(_OpgaveOmraadeNummerIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverMyndighedHentOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverMyndighedHentOutput")
    public JAXBElement<OpgaverMyndighedHentOutputType> createOpgaverMyndighedHentOutput(OpgaverMyndighedHentOutputType value) {
        return new JAXBElement<OpgaverMyndighedHentOutputType>(_OpgaverMyndighedHentOutput_QNAME, OpgaverMyndighedHentOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaveOmraadeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveOmraade")
    public JAXBElement<OpgaveOmraadeType> createOpgaveOmraade(OpgaveOmraadeType value) {
        return new JAXBElement<OpgaveOmraadeType>(_OpgaveOmraade_QNAME, OpgaveOmraadeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveNummerIdentifikator")
    public JAXBElement<String> createOpgaveNummerIdentifikator(String value) {
        return new JAXBElement<String>(_OpgaveNummerIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaveIndgangType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaveIndgang")
    public JAXBElement<OpgaveIndgangType> createOpgaveIndgang(OpgaveIndgangType value) {
        return new JAXBElement<OpgaveIndgangType>(_OpgaveIndgang_QNAME, OpgaveIndgangType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "HovedOmraadeNummerIdentifikator")
    public JAXBElement<String> createHovedOmraadeNummerIdentifikator(String value) {
        return new JAXBElement<String>(_HovedOmraadeNummerIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "RettetDato")
    public JAXBElement<XMLGregorianCalendar> createRettetDato(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RettetDato_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpgaverKLEHentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:form:1.0.0", name = "OpgaverKLEHentInput")
    public JAXBElement<OpgaverKLEHentInputType> createOpgaverKLEHentInput(OpgaverKLEHentInputType value) {
        return new JAXBElement<OpgaverKLEHentInputType>(_OpgaverKLEHentInput_QNAME, OpgaverKLEHentInputType.class, null, value);
    }

}
