//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjektType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjektType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oio:form:1.0.0}VersionType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}NavnTekst"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}BeskrivelseTekst"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}Soegeord" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjektType", propOrder = {
    "navnTekst",
    "beskrivelseTekst",
    "soegeord"
})
@XmlSeeAlso({
    OpgaveType.class,
    ServiceOmraadeBaseType.class,
    OpgaveOmraadeBaseType.class,
    HovedOmraadeBaseType.class
})
public class ObjektType
    extends VersionType
{

    @XmlElement(name = "NavnTekst", required = true)
    protected String navnTekst;
    @XmlElement(name = "BeskrivelseTekst", required = true)
    protected String beskrivelseTekst;
    @XmlElement(name = "Soegeord")
    protected List<SoegeordType> soegeord;

    /**
     * Gets the value of the navnTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavnTekst() {
        return navnTekst;
    }

    /**
     * Sets the value of the navnTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavnTekst(String value) {
        this.navnTekst = value;
    }

    /**
     * Gets the value of the beskrivelseTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeskrivelseTekst() {
        return beskrivelseTekst;
    }

    /**
     * Sets the value of the beskrivelseTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeskrivelseTekst(String value) {
        this.beskrivelseTekst = value;
    }

    /**
     * Gets the value of the soegeord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the soegeord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoegeord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoegeordType }
     * 
     * 
     */
    public List<SoegeordType> getSoegeord() {
        if (soegeord == null) {
            soegeord = new ArrayList<SoegeordType>();
        }
        return this.soegeord;
    }

}
