//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpgaveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpgaveType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oio:form:1.0.0}ObjektType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}FinanslovIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}LovgivningIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}MyndighedIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpgaveType", propOrder = {
    "opgaveNummerIdentifikator",
    "finanslovIndgang",
    "lovgivningIndgang",
    "myndighedIndgang"
})
public class OpgaveType
    extends ObjektType
{

    @XmlElement(name = "OpgaveNummerIdentifikator", required = true)
    protected String opgaveNummerIdentifikator;
    @XmlElement(name = "FinanslovIndgang")
    protected List<FinanslovIndgangType> finanslovIndgang;
    @XmlElement(name = "LovgivningIndgang")
    protected List<LovgivningIndgangType> lovgivningIndgang;
    @XmlElement(name = "MyndighedIndgang")
    protected List<MyndighedIndgangType> myndighedIndgang;

    /**
     * Gets the value of the opgaveNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpgaveNummerIdentifikator() {
        return opgaveNummerIdentifikator;
    }

    /**
     * Sets the value of the opgaveNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpgaveNummerIdentifikator(String value) {
        this.opgaveNummerIdentifikator = value;
    }

    /**
     * Gets the value of the finanslovIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finanslovIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinanslovIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinanslovIndgangType }
     * 
     * 
     */
    public List<FinanslovIndgangType> getFinanslovIndgang() {
        if (finanslovIndgang == null) {
            finanslovIndgang = new ArrayList<FinanslovIndgangType>();
        }
        return this.finanslovIndgang;
    }

    /**
     * Gets the value of the lovgivningIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lovgivningIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLovgivningIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LovgivningIndgangType }
     * 
     * 
     */
    public List<LovgivningIndgangType> getLovgivningIndgang() {
        if (lovgivningIndgang == null) {
            lovgivningIndgang = new ArrayList<LovgivningIndgangType>();
        }
        return this.lovgivningIndgang;
    }

    /**
     * Gets the value of the myndighedIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the myndighedIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMyndighedIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MyndighedIndgangType }
     * 
     * 
     */
    public List<MyndighedIndgangType> getMyndighedIndgang() {
        if (myndighedIndgang == null) {
            myndighedIndgang = new ArrayList<MyndighedIndgangType>();
        }
        return this.myndighedIndgang;
    }

}
