//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpgaverKLEHentInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpgaverKLEHentInputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}EmneHandlingFacetTekst"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}FormDybdeKvantitet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpgaverKLEHentInputType", propOrder = {
    "emneHandlingFacetTekst",
    "formDybdeKvantitet"
})
public class OpgaverKLEHentInputType {

    @XmlElement(name = "EmneHandlingFacetTekst", required = true)
    protected String emneHandlingFacetTekst;
    @XmlElement(name = "FormDybdeKvantitet")
    protected BigInteger formDybdeKvantitet;

    /**
     * Gets the value of the emneHandlingFacetTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmneHandlingFacetTekst() {
        return emneHandlingFacetTekst;
    }

    /**
     * Sets the value of the emneHandlingFacetTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmneHandlingFacetTekst(String value) {
        this.emneHandlingFacetTekst = value;
    }

    /**
     * Gets the value of the formDybdeKvantitet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFormDybdeKvantitet() {
        return formDybdeKvantitet;
    }

    /**
     * Sets the value of the formDybdeKvantitet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFormDybdeKvantitet(BigInteger value) {
        this.formDybdeKvantitet = value;
    }

}
