//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpgaveOmraadeBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpgaveOmraadeBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oio:form:1.0.0}ObjektType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}OpgaveOmraadeNummerIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}DomaenebestyrelseIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}FinanslovIndgang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}KLEindgang" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpgaveOmraadeBaseType", propOrder = {
    "opgaveOmraadeNummerIdentifikator",
    "domaenebestyrelseIndgang",
    "finanslovIndgang",
    "klEindgang"
})
@XmlSeeAlso({
    OpgaveOmraadeType.class
})
public class OpgaveOmraadeBaseType
    extends ObjektType
{

    @XmlElement(name = "OpgaveOmraadeNummerIdentifikator", required = true)
    protected String opgaveOmraadeNummerIdentifikator;
    @XmlElement(name = "DomaenebestyrelseIndgang")
    protected List<DomaenebestyrelseIndgangType> domaenebestyrelseIndgang;
    @XmlElement(name = "FinanslovIndgang")
    protected List<FinanslovIndgangType> finanslovIndgang;
    @XmlElement(name = "KLEindgang")
    protected List<KLEindgangType> klEindgang;

    /**
     * Gets the value of the opgaveOmraadeNummerIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpgaveOmraadeNummerIdentifikator() {
        return opgaveOmraadeNummerIdentifikator;
    }

    /**
     * Sets the value of the opgaveOmraadeNummerIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpgaveOmraadeNummerIdentifikator(String value) {
        this.opgaveOmraadeNummerIdentifikator = value;
    }

    /**
     * Gets the value of the domaenebestyrelseIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domaenebestyrelseIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomaenebestyrelseIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomaenebestyrelseIndgangType }
     * 
     * 
     */
    public List<DomaenebestyrelseIndgangType> getDomaenebestyrelseIndgang() {
        if (domaenebestyrelseIndgang == null) {
            domaenebestyrelseIndgang = new ArrayList<DomaenebestyrelseIndgangType>();
        }
        return this.domaenebestyrelseIndgang;
    }

    /**
     * Gets the value of the finanslovIndgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finanslovIndgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinanslovIndgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinanslovIndgangType }
     * 
     * 
     */
    public List<FinanslovIndgangType> getFinanslovIndgang() {
        if (finanslovIndgang == null) {
            finanslovIndgang = new ArrayList<FinanslovIndgangType>();
        }
        return this.finanslovIndgang;
    }

    /**
     * Gets the value of the klEindgang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the klEindgang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKLEindgang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KLEindgangType }
     * 
     * 
     */
    public List<KLEindgangType> getKLEindgang() {
        if (klEindgang == null) {
            klEindgang = new ArrayList<KLEindgangType>();
        }
        return this.klEindgang;
    }

}
