//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoegeordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoegeordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}OrdenMaal"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}SoegeordTekst"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoegeordType", propOrder = {
    "ordenMaal",
    "soegeordTekst"
})
public class SoegeordType {

    @XmlElement(name = "OrdenMaal", required = true)
    protected BigInteger ordenMaal;
    @XmlElement(name = "SoegeordTekst", required = true)
    protected String soegeordTekst;

    /**
     * Gets the value of the ordenMaal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdenMaal() {
        return ordenMaal;
    }

    /**
     * Sets the value of the ordenMaal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdenMaal(BigInteger value) {
        this.ordenMaal = value;
    }

    /**
     * Gets the value of the soegeordTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoegeordTekst() {
        return soegeordTekst;
    }

    /**
     * Sets the value of the soegeordTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoegeordTekst(String value) {
        this.soegeordTekst = value;
    }

}
