//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 02:41:31 PM CEST 
//


package dk.formonline.formoperationer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:form:1.0.0}VersionIdentifikator"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}OprettetDato"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}RettetDato" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}UdgaaetDato" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:form:1.0.0}UuidIdentifikator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionType", propOrder = {
    "versionIdentifikator",
    "oprettetDato",
    "rettetDato",
    "udgaaetDato",
    "uuidIdentifikator"
})
@XmlSeeAlso({
    ObjektType.class
})
public class VersionType {

    @XmlElement(name = "VersionIdentifikator", required = true)
    protected String versionIdentifikator;
    @XmlElement(name = "OprettetDato", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oprettetDato;
    @XmlElement(name = "RettetDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rettetDato;
    @XmlElement(name = "UdgaaetDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar udgaaetDato;
    @XmlElement(name = "UuidIdentifikator", required = true)
    protected String uuidIdentifikator;

    /**
     * Gets the value of the versionIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionIdentifikator() {
        return versionIdentifikator;
    }

    /**
     * Sets the value of the versionIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionIdentifikator(String value) {
        this.versionIdentifikator = value;
    }

    /**
     * Gets the value of the oprettetDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOprettetDato() {
        return oprettetDato;
    }

    /**
     * Sets the value of the oprettetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOprettetDato(XMLGregorianCalendar value) {
        this.oprettetDato = value;
    }

    /**
     * Gets the value of the rettetDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRettetDato() {
        return rettetDato;
    }

    /**
     * Sets the value of the rettetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRettetDato(XMLGregorianCalendar value) {
        this.rettetDato = value;
    }

    /**
     * Gets the value of the udgaaetDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUdgaaetDato() {
        return udgaaetDato;
    }

    /**
     * Sets the value of the udgaaetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUdgaaetDato(XMLGregorianCalendar value) {
        this.udgaaetDato = value;
    }

    /**
     * Gets the value of the uuidIdentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidIdentifikator() {
        return uuidIdentifikator;
    }

    /**
     * Sets the value of the uuidIdentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidIdentifikator(String value) {
        this.uuidIdentifikator = value;
    }

}
