//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 07:05:22 AM CET 
//


package dk.kleonline.emner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kle-online.dk/rest/resources/emneplan}EmneNr"/>
 *         &lt;element ref="{http://www.kle-online.dk/rest/resources/emneplan}UUID" minOccurs="0"/>
 *         &lt;element ref="{http://www.kle-online.dk/rest/resources/emneplan}EmneTitel"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmneType", namespace = "http://www.kle-online.dk/rest/resources/emne/liste", propOrder = {
    "emneNr",
    "uuid",
    "emneTitel"
})
public class EmneType {

    @XmlElement(name = "EmneNr", namespace = "http://www.kle-online.dk/rest/resources/emneplan", required = true)
    protected String emneNr;
    @XmlElement(name = "UUID", namespace = "http://www.kle-online.dk/rest/resources/emneplan")
    protected String uuid;
    @XmlElement(name = "EmneTitel", namespace = "http://www.kle-online.dk/rest/resources/emneplan", required = true)
    protected String emneTitel;
    @XmlAttribute(name = "ref", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String ref;

    /**
     * Gets the value of the emneNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmneNr() {
        return emneNr;
    }

    /**
     * Sets the value of the emneNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmneNr(String value) {
        this.emneNr = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the emneTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmneTitel() {
        return emneTitel;
    }

    /**
     * Sets the value of the emneTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmneTitel(String value) {
        this.emneTitel = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

}
