//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 07:05:21 AM CET 
//


package dk.kleonline.hovedgrupper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HovedgruppeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HovedgruppeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kle-online.dk/rest/resources/emneplan}HovedgruppeNr"/>
 *         &lt;element ref="{http://www.kle-online.dk/rest/resources/emneplan}HovedgruppeTitel"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HovedgruppeType", namespace = "http://www.kle-online.dk/rest/resources/hovedgruppe/liste", propOrder = {
    "hovedgruppeNr",
    "hovedgruppeTitel"
})
public class HovedgruppeType {

    @XmlElement(name = "HovedgruppeNr", namespace = "http://www.kle-online.dk/rest/resources/emneplan", required = true)
    protected String hovedgruppeNr;
    @XmlElement(name = "HovedgruppeTitel", namespace = "http://www.kle-online.dk/rest/resources/emneplan", required = true)
    protected String hovedgruppeTitel;
    @XmlAttribute(name = "ref", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String ref;

    /**
     * Gets the value of the hovedgruppeNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedgruppeNr() {
        return hovedgruppeNr;
    }

    /**
     * Sets the value of the hovedgruppeNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedgruppeNr(String value) {
        this.hovedgruppeNr = value;
    }

    /**
     * Gets the value of the hovedgruppeTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHovedgruppeTitel() {
        return hovedgruppeTitel;
    }

    /**
     * Sets the value of the hovedgruppeTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHovedgruppeTitel(String value) {
        this.hovedgruppeTitel = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

}
