//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 07:05:21 AM CET 
//


package dk.kleonline.hovedgrupper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VejledningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VejledningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VejledningTekst" type="{http://www.kle-online.dk/rest/resources/emneplan}VejledningTekstType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VejledningType", propOrder = {
    "vejledningTekst"
})
public class VejledningType {

    @XmlElement(name = "VejledningTekst", required = true)
    protected VejledningTekstType vejledningTekst;

    /**
     * Gets the value of the vejledningTekst property.
     * 
     * @return
     *     possible object is
     *     {@link VejledningTekstType }
     *     
     */
    public VejledningTekstType getVejledningTekst() {
        return vejledningTekst;
    }

    /**
     * Sets the value of the vejledningTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link VejledningTekstType }
     *     
     */
    public void setVejledningTekst(VejledningTekstType value) {
        this.vejledningTekst = value;
    }

}
