//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 07:05:21 AM CET 
//


package dk.kleonline.grupper;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterTitelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FilterTitelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KommunalVand"/>
 *     &lt;enumeration value="PrivatVand"/>
 *     &lt;enumeration value="SaerligStoetteDelplan"/>
 *     &lt;enumeration value="DagtilbudDelplan"/>
 *     &lt;enumeration value="AeldreOmrådeDelPlan"/>
 *     &lt;enumeration value="FolkeskolenDelplan"/>
 *     &lt;enumeration value="JobcenterDelplan"/>
 *     &lt;enumeration value="FagsystemDelplan"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterTitelType")
@XmlEnum
public enum FilterTitelType {

    @XmlEnumValue("KommunalVand")
    KOMMUNAL_VAND("KommunalVand"),
    @XmlEnumValue("PrivatVand")
    PRIVAT_VAND("PrivatVand"),
    @XmlEnumValue("SaerligStoetteDelplan")
    SAERLIG_STOETTE_DELPLAN("SaerligStoetteDelplan"),
    @XmlEnumValue("DagtilbudDelplan")
    DAGTILBUD_DELPLAN("DagtilbudDelplan"),
    @XmlEnumValue("AeldreOmr\u00e5deDelPlan")
    AELDRE_OMRÅDE_DEL_PLAN("AeldreOmr\u00e5deDelPlan"),
    @XmlEnumValue("FolkeskolenDelplan")
    FOLKESKOLEN_DELPLAN("FolkeskolenDelplan"),
    @XmlEnumValue("JobcenterDelplan")
    JOBCENTER_DELPLAN("JobcenterDelplan"),
    @XmlEnumValue("FagsystemDelplan")
    FAGSYSTEM_DELPLAN("FagsystemDelplan");
    private final String value;

    FilterTitelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FilterTitelType fromValue(String v) {
        for (FilterTitelType c: FilterTitelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
