//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 07:05:21 AM CET 
//


package dk.kleonline.grupper;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for KLEAdministrativInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KLEAdministrativInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OprettetDato" type="{http://www.kle-online.dk/rest/resources/emneplan}OprettetDatoType"/>
 *         &lt;element name="RettetDato" type="{http://www.kle-online.dk/rest/resources/emneplan}RettetDatoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Historisk" type="{http://www.kle-online.dk/rest/resources/emneplan}HistoriskType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KLEAdministrativInfoType", propOrder = {
    "oprettetDato",
    "rettetDato",
    "historisk"
})
public class KLEAdministrativInfoType {

    @XmlElement(name = "OprettetDato", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oprettetDato;
    @XmlElement(name = "RettetDato")
    @XmlSchemaType(name = "date")
    protected List<XMLGregorianCalendar> rettetDato;
    @XmlElement(name = "Historisk")
    protected HistoriskType historisk;

    /**
     * Gets the value of the oprettetDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOprettetDato() {
        return oprettetDato;
    }

    /**
     * Sets the value of the oprettetDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOprettetDato(XMLGregorianCalendar value) {
        this.oprettetDato = value;
    }

    /**
     * Gets the value of the rettetDato property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rettetDato property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRettetDato().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getRettetDato() {
        if (rettetDato == null) {
            rettetDato = new ArrayList<XMLGregorianCalendar>();
        }
        return this.rettetDato;
    }

    /**
     * Gets the value of the historisk property.
     * 
     * @return
     *     possible object is
     *     {@link HistoriskType }
     *     
     */
    public HistoriskType getHistorisk() {
        return historisk;
    }

    /**
     * Sets the value of the historisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoriskType }
     *     
     */
    public void setHistorisk(HistoriskType value) {
        this.historisk = value;
    }

}
